xfs_repair: add prototype for alloc_ex_data()
3ac87fbf xfsprogs: fix inode crash in xfs_repair

un-static'd alloc_ex_data and used it in phase6.c,
but didn't put a prototype in a header, so:

 phase6.c: In function ‘mk_orphanage’:
 phase6.c:943: warning: implicit declaration of function ‘alloc_ex_data’

Fix it...

Signed-off-by: Eric Sandeen <sandeen@redhat.com>
Reviewed-by: Dave Chinner <dchinner@redhat.com>
Signed-off-by: Rich Johnston <rjohnston@sgi.com>

(cherry picked from commit 2e1622703bb5c01e5f6d5fa087999c768868aa0b)